// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: helloworld.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.helloworld;

@kotlin.jvm.JvmName("-initializehelloRequest")
public inline fun helloRequest(block: com.example.helloworld.HelloRequestKt.Dsl.() -> kotlin.Unit): com.example.helloworld.Helloworld.HelloRequest =
  com.example.helloworld.HelloRequestKt.Dsl._create(com.example.helloworld.Helloworld.HelloRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.example.helloworld.HelloRequest`
 */
public object HelloRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.helloworld.Helloworld.HelloRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.helloworld.Helloworld.HelloRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.helloworld.Helloworld.HelloRequest = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.helloworld.Helloworld.HelloRequest.copy(block: `com.example.helloworld`.HelloRequestKt.Dsl.() -> kotlin.Unit): com.example.helloworld.Helloworld.HelloRequest =
  `com.example.helloworld`.HelloRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

