/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello_04

import com.mine.sum

class App {
    val greeting: Int
        get() {
            return sum(2, 3)
        }
}

fun main() {
    println(App().greeting)
}
