/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello_05

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = App()
        
    }
}
