/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello_04

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertEquals(classUnderTest.greeting, 5)
    }
}
